services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
            args:
                ENV_VARIABLE: ${ENV_VARIABLE}
                NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
        restart: always
        ports:
            - 3000:3000
        networks:
            - blog-tech

    # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
    blog-tech:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
