services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./src:/var/www/html/src:ro
      - ./index.php:/var/www/html/index.php:ro
      - ./public:/var/www/html/public:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
    networks:
      - app_network
    restart: unless-stopped

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/src
      - ./index.php:/var/www/html/index.php
      - ./public:/var/www/html/public
      - ./logs:/var/www/html/logs
    environment:
      - DB_HOST=mysql
      - DB_NAME=${DB_NAME:-myapp_db}
      - DB_USER=${DB_USER:-myuser}
      - DB_PASSWORD=${DB_PASSWORD:-mypassword}
      - APP_ENV=${APP_ENV:-production}
      - DEBUG=${DEBUG:-false}
    depends_on:
      - mysql
    networks:
      - app_network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-myapp_db}
      MYSQL_USER: ${DB_USER:-myuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-mypassword}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - '3306:3306'
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge

